version: '3'

services:
  nginx:
    container_name: nginx
    volumes:
    - wordpress:/var/www/wordpress
    networks:
    - inception
    ports:
      - "443:443"
    depends_on:
    - wordpress
    build: ./requirements/nginx/
    image: nginx:1.0
    env_file: .env
    restart: on-failure

  mariadb:
    container_name: mariadb
    volumes:
    - mariadb:/var/lib/mysql
    networks:
    - inception
    expose:
    - :3306
    build: ./requirements/mariadb/
    image: mariadb:1.0
    env_file: .env
    restart: on-failure

  wordpress:
    container_name: wordpress
    volumes:
    - wordpress:/var/www/wordpress
    networks:
    - inception
    expose:
    - :9000
    depends_on:
    - mariadb
    build: ./requirements/wordpress/
    image: wordpress:1.0
    env_file: .env
    restart: on-failure

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: '/home/Emily/data/wordpress'

  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: '/home/Emily/data/mariadb'

networks:
  inception:
    name: inception
    # driver: bridge